# Template per eventi calendario Microsoft Teams
# Variabili disponibili: {Nome}, {Codice}, {Data}, {Area}
# Note: Il link Teams viene inserito automaticamente da Outlook

calendar_event:
  subject: |
    Formazione {Nome}
  
  body: |
    🎓 Formazione Programmata!
    
    🎯 Area: {Area}    
    📅 Data: {Data}
    📋 Codice: {Codice}

    
    ---
    Per dubbi o informazioni contattare il responsabile formazioni.
